/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import functions.Registration;
import functions.UpdateTerm;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import validation.Validator;

/**
 *
 * @author Earl
 */
public final class AdminMain extends javax.swing.JFrame {

    /**
     * Creates new form AdminMain
     */
    public AdminMain() throws SQLException {
        this.setTitle("SCIS Student Logbook Admin Module");
        setResizable(false);
        initComponents();
        setLocationRelativeTo(null);
        term.setText(getTerm());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textsubject = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        SCISLogo = new javax.swing.JLabel();
        headTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        term = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        viewCodeButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        addRemoveSubjectsButton = new javax.swing.JButton();
        addRemoveFacultyButton = new javax.swing.JButton();
        activateDeactivateAccountsButton = new javax.swing.JButton();
        manLabel = new javax.swing.JLabel();
        generateStudentsListButton = new javax.swing.JButton();
        generateLogsButton = new javax.swing.JButton();
        genLabel = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SCISLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/SCIS Logo.png"))); // NOI18N
        jPanel1.add(SCISLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        headTitle.setFont(new java.awt.Font("Bebas", 0, 135)); // NOI18N
        headTitle.setForeground(new java.awt.Color(51, 51, 51));
        headTitle.setText("scis");
        jPanel1.add(headTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("STUDENT LOGBOOK");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Admin Module");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jButton1.setText("Create an Admin Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        term.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        term.setForeground(new java.awt.Color(102, 102, 102));
        term.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        term.setText("Term");
        term.setToolTipText("");
        term.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        term.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                termMouseClicked(evt);
            }
        });
        jPanel1.add(term, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jButton2.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jButton2.setText("LOGOUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, -1, -1));

        viewCodeButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        viewCodeButton.setText("View Password Recovery Code");
        viewCodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCodeButtonActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jButton4.setText("Update Academic Term");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        addRemoveSubjectsButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        addRemoveSubjectsButton.setText("Add/Remove Subjects");
        addRemoveSubjectsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRemoveSubjectsButtonActionPerformed(evt);
            }
        });

        addRemoveFacultyButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        addRemoveFacultyButton.setText("Add/Remove Faculty");
        addRemoveFacultyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRemoveFacultyButtonActionPerformed(evt);
            }
        });

        activateDeactivateAccountsButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        activateDeactivateAccountsButton.setText("Activate/Deactivate Accounts");
        activateDeactivateAccountsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activateDeactivateAccountsButtonActionPerformed(evt);
            }
        });

        manLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        manLabel.setText("Management:");

        generateStudentsListButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        generateStudentsListButton.setText("Student List");
        generateStudentsListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateStudentsListButtonActionPerformed(evt);
            }
        });

        generateLogsButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        generateLogsButton.setText("Logs");
        generateLogsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateLogsButtonActionPerformed(evt);
            }
        });

        genLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        genLabel.setText("Generate Reports:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genLabel)
                    .addComponent(manLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(generateLogsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(generateStudentsListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(activateDeactivateAccountsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addRemoveFacultyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addRemoveSubjectsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewCodeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(genLabel)
                .addGap(13, 13, 13)
                .addComponent(generateLogsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(generateStudentsListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(manLabel)
                .addGap(13, 13, 13)
                .addComponent(activateDeactivateAccountsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(addRemoveFacultyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(addRemoveSubjectsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(viewCodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateStudentsListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateStudentsListButtonActionPerformed
        try {
            new functions.GenerateStudentList().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(AdminMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_generateStudentsListButtonActionPerformed

    private void generateLogsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateLogsButtonActionPerformed
        try {
            new functions.GenerateLogs().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(AdminMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_generateLogsButtonActionPerformed

    private void viewCodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCodeButtonActionPerformed
        new functions.ViewPasswordRecovery().setVisible(true);
    }//GEN-LAST:event_viewCodeButtonActionPerformed

    private void addRemoveSubjectsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRemoveSubjectsButtonActionPerformed
        try {
            new functions.AddRemoveSubjects().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(AdminMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addRemoveSubjectsButtonActionPerformed

    private void addRemoveFacultyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRemoveFacultyButtonActionPerformed
        try {
            new functions.AddRemoveFaculty().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(AdminMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addRemoveFacultyButtonActionPerformed

    private void activateDeactivateAccountsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activateDeactivateAccountsButtonActionPerformed
        try {
            new functions.ActivateDeactivateAccounts().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(AdminMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_activateDeactivateAccountsButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new UpdateTerm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void termMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_termMouseClicked

    }//GEN-LAST:event_termMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Registration reg = null;
        try {
            reg = new Registration();
        } catch (SQLException ex) {
            Logger.getLogger(LoginAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        reg.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked

    }//GEN-LAST:event_jLabel13MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        new LoginAdmin().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private Boolean validateAccount(String id) throws SQLException {
        String status = null;
        Connection con;
        PreparedStatement ps;
        boolean condition = false;
        con = jdbc.connection.DBConnection.connectDB();
        String query = "SELECT idnumber FROM students where idnumber= ? ; ";
        ps = con.prepareStatement(query);
        ps.setString(1, id);
        ResultSet rs = ps.executeQuery();
        if (rs.next()) {
            condition = true;
        }
        rs.close();
        ps.close();
        con.close();

        return condition;
    }

    public String[] term() throws SQLException {
        Connection con;
        con = jdbc.connection.DBConnection.connectDB();
        Statement stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                ResultSet.CONCUR_UPDATABLE);
        String query = "SELECT DISTINCT term FROM logs";
        ResultSet rs = stmt.executeQuery(query);

        ArrayList list = new ArrayList();

        while (rs.next()) {
            list.add(rs.getString("term"));
        }
        String[] term = new String[list.size()];
        list.toArray(term);
        return term;

    }

    public String[] getAccountIDs(String subject) throws SQLException {
        Connection con;
        con = jdbc.connection.DBConnection.connectDB();
        PreparedStatement ps = null;

        String query = "SELECT account_id from accounts where subjid = ?";

        ps = con.prepareStatement(query);
        ps.setString(1, getSubjectID(subject));

        ResultSet rs = ps.executeQuery();

        ArrayList list = new ArrayList();

        while (rs.next()) {
            list.add(rs.getString("account_id"));
        }
        String[] accountIDs = new String[list.size()];
        list.toArray(accountIDs);

        return accountIDs;
    }

    private String getSubjectID(String subject) throws SQLException {
        String subjid = null;
        Connection con;
        PreparedStatement ps;

        con = jdbc.connection.DBConnection.connectDB();
        String query = "select subjid from subject where subj_title = ?";
        ps = con.prepareStatement(query);

        ps.setString(1, subject);

        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            subjid = rs.getString("subjid");
        }

        rs.close();
        ps.close();
        con.close();

        return subjid;
    }

    private String getTerm() throws SQLException {
        Connection con = jdbc.connection.DBConnection.connectDB();
        Statement stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                ResultSet.CONCUR_UPDATABLE);
        String current_term = null;

        String query = "SELECT * from current_term where term_id = 1";
        ResultSet rs = stmt.executeQuery(query);

        if (rs.next()) {
            current_term = rs.getString("semester") + ", A.Y. " + rs.getString("academic_year");
        }
        return current_term;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new AdminMain().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AdminMain.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SCISLogo;
    private javax.swing.JButton activateDeactivateAccountsButton;
    private javax.swing.JButton addRemoveFacultyButton;
    private javax.swing.JButton addRemoveSubjectsButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel genLabel;
    private javax.swing.JButton generateLogsButton;
    private javax.swing.JButton generateStudentsListButton;
    private javax.swing.JLabel headTitle;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel manLabel;
    private javax.swing.JLabel term;
    private javax.swing.JTextField textsubject;
    private javax.swing.JButton viewCodeButton;
    // End of variables declaration//GEN-END:variables

}
