/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package createexcel;


import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Logger;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;

/**
 *
 * @author invinoveritas
 */
public class selectFile extends javax.swing.JFrame {

    /**
     * Creates new form selectFile
     */
    public selectFile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rad_prac_log = new javax.swing.JRadioButton();
        rad_log_prog = new javax.swing.JRadioButton();
        rad_studacc_prac = new javax.swing.JRadioButton();
        rad_studacc_prog = new javax.swing.JRadioButton();
        filter_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Nanum Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Select table to export:");

        rad_prac_log.setText("Practicum 1 Log Book");

        rad_log_prog.setText("IT Project Log Book");
        rad_log_prog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_log_progActionPerformed(evt);
            }
        });

        rad_studacc_prac.setText("Students Account (Practicum 1)");

        rad_studacc_prog.setText("Students' Account (IT Project)");
        rad_studacc_prog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_studacc_progActionPerformed(evt);
            }
        });

        filter_button.setText("Filter");
        filter_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filter_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rad_studacc_prog)
                            .addComponent(rad_studacc_prac)
                            .addComponent(rad_log_prog)
                            .addComponent(rad_prac_log))
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(filter_button)
                        .addGap(133, 133, 133))))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(rad_prac_log)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rad_log_prog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rad_studacc_prac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rad_studacc_prog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filter_button)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filter_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filter_buttonActionPerformed
        Connection conn;
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost/scislog", "root", "root");
            PreparedStatement stmt = null;
            Statement st = conn.createStatement();
            ResultSet rs = null;

            if (rad_prac_log.isSelected()) {
                rs = stmt.executeQuery("SELECT * FROM log_practicum;");
                HSSFWorkbook workbook = new HSSFWorkbook();
                HSSFSheet worksheet = workbook.createSheet("Practicum 1");
                HSSFRow heading = worksheet.createRow((short) 0);
                heading.createCell((short) 0).setCellValue("logid");
                heading.createCell((short) 0).setCellValue("idnum");
                heading.createCell((short) 0).setCellValue("date");
                heading.createCell((short) 0).setCellValue("time_in");
                heading.createCell((short) 0).setCellValue("time_out");
                heading.createCell((short) 0).setCellValue("office");

                int index = 1;
                while (rs.next()) {
                    HSSFRow row = worksheet.createRow((short) index);
                    row.createCell((short) 0).setCellValue(rs.getInt(1));
                    row.createCell((short) 1).setCellValue(rs.getInt(2));
                    row.createCell((short) 2).setCellValue(rs.getString(3));
                    row.createCell((short) 3).setCellValue(rs.getString(4));
                    row.createCell((short) 4).setCellValue(rs.getString(5));
                    index++;
                }
                try (FileOutputStream fileOut = new FileOutputStream("/Users/invinoveritas/downloads/log.xlsx")) {
                    workbook.write(fileOut);
                }

                rs.close();
                conn.close();
            }
        } catch (SQLException | IOException x) {
        }
    }//GEN-LAST:event_filter_buttonActionPerformed

    private void rad_studacc_progActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_studacc_progActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rad_studacc_progActionPerformed

    private void rad_log_progActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_log_progActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rad_log_progActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(selectFile.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(selectFile.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(selectFile.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(selectFile.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new selectFile().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton filter_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel;
    private javax.swing.JRadioButton rad_log_prog;
    private javax.swing.JRadioButton rad_prac_log;
    private javax.swing.JRadioButton rad_studacc_prac;
    private javax.swing.JRadioButton rad_studacc_prog;
    // End of variables declaration//GEN-END:variables
}
